### ISSUE TITLE
Dependencies conflict with angular.dart dependencies

### ISSUE THREAD

**Issue by austincummings** [luizmineo/redstone.dart#68]
Hey @luizmineo,

I have a Dart app that is using your package and Angular.dart. Now when I go to run `pub get --verbose` I get an error about `route_hierarchical` clashing between redstone and angular. I was hoping you could update your dependencies so that these clashes won't happen anymore.

Thanks!

pubspec details
```
angular: ">=1.1.0 <2.0.0"
redstone: ">=0.5.19 <0.6.0"
redstone_mapper: ">=0.1.11 <0.2.0"
```
Error message
```
ERR : Incompatible version constraints on route_hierarchical:
    | - angular 1.1.0 depends on version >=0.6.1 <0.7.0
    | - redstone 0.5.19 depends on version >=0.5.0 <0.6.0
```

**Comment by luizmineo** [comment]
Thanks! Fixed in v0.5.20.
