### ISSUE TITLE
Get fqdn in the request object

### ISSUE THREAD

**Issue by sonoranDesert** [luizmineo/redstone.dart#69]
Is there are way to get the fqdn or hostname requested by the client?

I see that I can look at app.request.url and app.request.url.path, but I need the actual server name / hostname from the request.

For example, if my redstone app serves a request for http://example.com/myresource, I know that app.request object has the "/myresource" string, but there is now way to get "example.com".

I need this so that I can do a 302 redirect if an old hostname is used in the request.

BTW I love redstone. It's by far the best Dart web framework I've used.

**Comment by digitalfiz** [comment]
You should be able to get it via:

```dart
app.request.headers.get('Host')
```

**Comment by luizmineo** [comment]
You can access the complete url through the `shelf.Request` object:

```dart
app.request.shelfRequest.requestedUri
```

Let me know if that helps

**Comment by luizmineo** [comment]
If you still have any problem or doubts, please let me know
