### ISSUE TITLE
Upgrade analyzer dependency

### ISSUE THREAD

**Issue by cgarciae** [luizmineo/redstone.dart#70]
I am getting this error when adding `async_await` to the dependencies

> Pub get failed, [1] Resolving dependencies... Incompatible version
> constraints on analyzer:
> - angular 1.0.0 depends on version >=0.15.0 <0.19.0
> - di 3.3.1 depends on version >=0.15.0 <0.22.0
> - redstone_mapper 0.1.1 depends on version >=0.13.0 <0.14.0

The weird thing is that the new dependency `async_await` does not appear on the error, which leaves you to wonder why it doesn't appear without it. Anyway, is it possible for you to upgrade the analyzer constraint? As you see, if you use `0.15.0` and above it falls within the `angular` and `di` range.

Thanks!

**Comment by luizmineo** [comment]
Please upgrade to angular.dart 1.1.0. Angular 1.0 actually uses a lower analyzer version than async_await.

**Comment by luizmineo** [comment]
If you still have any problems or doubts, please let me know.

**Comment by cgarciae** [comment]
It seemed to work great. Thanks a lot!
ᐧ
