### ISSUE TITLE
Redstone mapper transfromer not building main.dart.js

### ISSUE THREAD

**Issue by cgarciae** [luizmineo/redstone.dart#72]
After a tough debbuging session, I found that creating a field like this

´´´dart
@Field() Map map;
´´´
confuses the Redston mapper transformer into not compiling the main file. I'll expand the wiki to warn against this if the fix is not trivial.

**Comment by luizmineo** [comment]
Thanks! I've published redstone_mapper v0.1.12 with a fix for this.

Also, be sure to upgrade to redstone.dart v0.5.20. If you are also using angular, please upgrade to v1.1.0.
