### ISSUE TITLE
Route handlers not scanned when not located in main.dart

### ISSUE THREAD

**Issue by Pacane** [luizmineo/redstone.dart#73]
I'm trying to do this: 

```dart
// in games.dart
class Games {
  @app.Route("/")
  helloWorld() => "Hello, World!";
}

// in main.dart

main () {
  app.setupConsoleLog();
  app.start(port:3010);
}
```

and the server starts fine, but doesn't register the `GET` handler on `/`. I tried adding this
```
  app.addModule(new Module()..bind(Games));
``` 

just before the call to `start()` but it won't help.

Do I really have to keep the annotations in main.dart ?

**Comment by luizmineo** [comment]
No, you don't. But you need to annotate your classes with `@Group`

Example:

```dart
@app.Group("/")
class Games {
  @app.Route("/")
  helloWorld() => "Hello, World!";
}
```

Or:

```dart
@app.Group("/")
class Games {
  @app.DefaultRoute()
  helloWorld() => "Hello, World!";
}
```

**Comment by Pacane** [comment]
Thanks, got it working! Also, nice job on this framework, it looks very good, and the documentation is pretty nice. Keep up the good work.
