### ISSUE TITLE
Question: Routes with optional extension

### ISSUE THREAD

**Issue by austincummings** [luizmineo/redstone.dart#76]
Hello again,

First off I would like to say I've been using your library for awhile and it is absolutely great to work with. Now I was wondering if there is a way to have a route that has an optional extension/suffix. I see that the `@DefaultRoute` annotation has a `pathSuffix`, but I would like to have one route that catches `/queries/1.json` and `/queries/1`. Then have that route run the same logic despite the additional extension. This is for a RESTful API.

Thanks!

**Comment by luizmineo** [comment]
Try this:

```dart
@app.Route('/queries/1.json')
@app.Route('/queries/1')
myService() {
  ...
}
```

Maybe not a proper solution, but it works.

**Comment by austincummings** [comment]
That works for me. Thanks.
