### ISSUE TITLE
Breaking change with `encode` and `decode`?

### ISSUE THREAD

**Issue by cgarciae** [luizmineo/redstone.dart#78]
I've recently checked the documentation and notice that the new functions `encode` and `decode` are being promoted as a replace for `encodeJson` and `decodeJson`.

1. No example was given on how to use `decode`
2. Can you still use `encodeJson` and `decodeJson`? If not, it would be better to deprecate methods and create new ones instead of refactoring as to give people a chance to migrate without braking their code.

**Comment by luizmineo** [comment]
Actually, `encodeJson` and `decodeJson` are newer than `decode` and `encode`, and they aren't replacements, but auxiliary functions

* `encode` and `decode` produces and consumes `Map` objects
* `encodeJson` and `decodeJson` produces and consumes `String` objects. They are useful if you don't want to invoke the JSON codec from `dart:convert`, to translate between JSON strings and Map objects.

**Comment by cgarciae** [comment]
Ohh, great to hear. I was surprise by the change tho. Thanks!
